config/routes.rb
TimesheetBo::Application.routes.draw do
  get "additional_infos/show"

  match 'home' => 'home#index'

  resource :session

  resources :time_logs do
    member do
      post 'finish'

    end

  end

  resources :users do

  end

  root :to => "home#index"

end

app/models/time_log.rb
class TimeLog < ActiveRecord::Base

  belongs_to :bill_date

  acts_as_list :scope => :bill_date

  validates_presence_of :start_time
  validates_presence_of :title
  validates_presence_of :bill_date

  after_create :update_duration

  validates_uniqueness_of :start_time, :scope => :bill_date_id

  before_destroy :update_previous

  before_create :update_reference_title


  belongs_to :issue, :foreign_key => 'reference_id'

  validate :end_time_before_start_time, :on => :update

  def initialize(options)
    super(options)
    self.start_time = Time.now
    self.bill_date = BillDate.find_by_date(Date.today)
  end


  def end_time_before_start_time
    unless self.end_time.blank? or (self.end_time > self.start_time)
      return false
    end
  end

  def update_reference_title
    unless self.reference_id.blank?
      subject = Issue.get_subject(self.reference_id)
      self.title = subject unless subject.blank?
    end
  end

  def update_duration
    self.bill_date.reorder
    self.reload

    lower_time_log = self.lower_item
    higher_item = self.higher_item

    if lower_time_log or (self.end_time && self.lower_item.blank?)
      self.end_time = lower_time_log.start_time if lower_time_log
      self.calculate_duration
    else
      self.duration = nil
      self.save
    end

    if higher_item
      higher_item.end_time = self.start_time
      higher_item.calculate_duration
    end

  end



  def calculate_duration
    if self.end_time && self.start_time
      self.duration = self.end_time - self.start_time
    else
      self.duration = nil
    end
    self.save
  end

  def update_previous
    unless self.higher_item.blank?
      higher_item = self.higher_item
      higher_item.end_time = self.lower_item ? self.lower_item.start_time : nil
      higher_item.calculate_duration
      higher_item.save
    end
  end


end

app/controllers/time_logs_controller.rb
class TimeLogsController < ApplicationController
#  before_filter :ensure_signed_in

  def index
    params[:user_id] = 1
    @user = params[:user_id].blank? ? current_user : User.find(params[:user_id])
    @bill_dates = BillDate.all
    @date = BillDate.find_by_date(params[:date]) if params[:date]
    @date ||= BillDate.find_or_create_by_date(Date.current)
    @time_logs = @date.time_logs.order("start_time ASC")

    if params[:time_log_id]
      @time_log = TimeLog.find(params[:time_log_id])
    else
      @time_log = TimeLog.new(:bill_date => @date)
    end

    @partial = case params[:type]
                 when 'ticket'
                   'form_ticket'
                 else

               end


  end

  def new

  end

  def edit
    redirect_to time_logs_path(params[:bill_date_id], :time_log_id => params[:id])
  end

  def update
    @time_log = TimeLog.find(params[:id])
    params[:time_log][:start_time] = params[:date][:hour] + ':' + params[:date][:minute]
    if @time_log.update_attributes(params[:time_log])
      @time_log.update_duration
      redirect_to time_logs_path(params[:bill_date_id])
    else
      flash[:warning] = "Update unsuccessful"
    end
  end

  def create

    if params[:date] && params[:date][:hour] && params[:date][:hour]
      params[:time_log][:start_time] ="#{params[:date][:hour]}:#{params[:date][:minute]}"
    end


    @time_log = TimeLog.create(params[:time_log])


    if @time_log.valid?
      redirect_to time_logs_path(:bill_date => params[:time_log][:bill_date])
    else
      flash[:warning] = "There was a problem #{@time_log.errors.full_messages}"
      @date = @time_log.bill_date
      @bill_dates = BillDate.all
      @time_logs = @date.time_logs
      render :action => :index
    end

  end

  def destroy
    log = TimeLog.find(params[:id])
    date = log.bill_date
    log.destroy
    redirect_to time_logs_path(:bill_date => date)
  end

  def finish
    bill_date = BillDate.find(params[:id])
    last_log = bill_date.time_logs.last
    if params[:date] && params[:date][:hour] && params[:date][:minute]
      last_log.end_time = DateTime.new(bill_date.year,
                                       bill_date.month,
                                       bill_date.day,
                                       params[:date][:hour].to_i,
                                       params[:date][:minute].to_i)
    else
      last_log.end_time = DateTime.now
    end


    last_log.save
    last_log.update_duration

    redirect_to time_logs_path(:bill_date => bill_date)

  end

  #to-do filtered by user
  def self.favourites
    current_user = User.first
    User.timelogs

  end

end

app/helpers/time_logs_helper.rb
module TimeLogsHelper
  def short_cut(button_name)
    truncate(button_name, :length => 30)
  end


end

app/views/time_logs/_form.html.erb
<%= f.hidden_field :bill_date_id %>
<%= f.label :start_time %>

<%= select_hour(@time_log.new_record? ? Time.current : @time_log.start_time) %>

<%= select_minute(@time_log.new_record? ? Time.current : @time_log.start_time, :minute_step => 5) %>

<br/>

<p>
  <%= f.label :reference_id %>
  <%= f.text_field :reference_id %>
</p>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description %>
  <%= f.text_area :description, :rows => 2 %>
</p>
<p>
  <%= f.label :is_break %>
  <%= f.check_box :is_break %>
</p>

<p>
  <%= f.label :is_favourite %>
  <%= f.check_box :is_favourite %>
</p>
<br/>
<%= f.submit @time_log.valid? ? "Update" : "Create" %>

app/views/time_logs/_form_ticket.html.erb
<% form_for :time_log, @time_log, :url => time_logs_path, :method => :post do |form|%>
    <p>
      <label>Ticket Number</label>
      <%= form.text_field :reference_id %>
    </p>
<% end %>

app/views/time_logs/_time_log_selector.html.erb
<div class='favourite_div'>
  <% form_for :time_log, @time_log, :url => time_logs_path, :method => :post do |form| %>
      <%= form.hidden_field :is_break, :value => true %>
      <%= form.hidden_field :title, :value => 'Break' %>
      <%= button_to "Take a break", time_logs_path, :class => "fat_button" %>

  <% end %>

  <% form_for :time_log, @time_log, :url => time_logs_path, :method => :post do |form| %>
      <%= form.hidden_field :title, :value => 'Meeting' %>
      <%= button_to "Meeting", time_logs_path(:name => 'meeting'), :class => "fat_button" %>
  <% end %>

  <% form_tag time_logs_path, :method => :get do %>
      <%= hidden_field_tag :type, 'ticket' %>
      <%= button_to "Ticket", {}, :class => "fat_button" %>
  <% end %>

  <% form_tag time_logs_path, :method => :get do %>
      <%= hidden_field_tag :time_log %>
      <%= button_to "Others", {}, :class => "fat_button" %>
  <% end %>
</div>

<% User.first.favourite_time_logs.each do |favourite| %>
    <div class='favourite_div'>
      <% form_for :time_log, @time_log, :url => time_logs_path, :method => :post do |form| %>
          <%= form.hidden_field :is_break, :value => favourite.is_break? %>
          <%= form.hidden_field :reference_id, :value => favourite.reference_id %>
          <%= form.hidden_field :title, :value => favourite.title %>
          <%= form.hidden_field :description, :value => favourite.description %>
          <%= button_to "#{short_cut(favourite.title)}", {}, :class => "favorite_button" %>
      <% end %>
    </div>
<% end %>

app/views/time_logs/index.html.erb
<h1><%= @date.date.to_time.strftime("%d %B, %Y (%A)") %> </h1>
<div class="timesheet">
  <table cellspacing="0" cellpadding="0">
    <thead>
    <tr>
      <td class='time'>Time</td>
      <td class='title'>Title</td>
      <td class='duration'>Duration</td>
      <td class='actions'>Actions</td>
    </tr>
    </thead>
  </table>
  <div class='content'>
    <table cellspacing="0" cellpadding="0">
      <tbody>
      <% @time_logs.each do |log| %>
          <tr class="<%= cycle("odd", "even") %> <%= 'break' if log.is_break? %>">
            <td class='time'><%= log.start_time.strftime("%H:%M") %></td>
            <td class='title'><%= truncate(log.title, :length => 160) %>
              <br/>

              <div class='description'><%= truncate(h(log.description), :length => 70) %></div>
            </td>
            <td class='duration'>
              <%= log.duration.blank? ? '' : distance_of_time_in_words(log.start_time, log.end_time, true, :only => ["minutes", "hours"]) %>
              <%= log.is_break? ? '(break)' : '' %>
            </td>
            <td class='actions'>
              <%= link_to 'Edit', edit_time_log_path(log), :method => :get %>
              <%= link_to 'Delete', time_log_path(log), :method => :delete %>
            </td>
          </tr>
      <% end %>
      <tr>
        <td colspan="4"><%= @date.finished_at if @date %></td>
      </tr>
      </tbody>
    </table>
  </div>
</div>




<% content_for :left_panel do %>
    <% @bill_dates.each do |bill_date| %>
        <%= link_to bill_date.date, time_logs_path(:date => bill_date.date) %><br/>
    <% end %>
    <br/>
    <label>Started at</label>
    <%= short_time @date.started_at %>
    <br/><br/>
    Break: <%= distance_of_time(@date.total_break) if @date %>
    <br/><br/>
    <label>Finished at</label>
    <%= short_time @date.finished_at %>
    <br/><br/>
    Total : <%= distance_of_time(@date.total_hours) if @date %>
    <br/><br/>
    <%= button_to "Update Time", time_logs_path, :method => :get %>

    <% form_tag finish_time_log_path(@date), :method => :post do %>
        <%= select_hour(Time.current, :field_name => :hour) %>
        <%= select_minute(Time.current, :field_name => :minute, :minute_step => 5) %>
        <%= submit_tag "Finish" %>
    <% end %>



<% end %>

<div style="float:left">
  <% if params[:time_log_id] || params[:time_log] %>
      <%= form_for @time_log, :as => :time_log, :html => {:method => (@time_log.valid? ? :put : :post), :class => 'report'} do |f| %>
          <%= hidden_field_tag :bill_date_id, @date.id %>
          <%= render :partial => 'form', :locals => {:f => f} %>
      <% end %>
      <%= button_to :cancel, time_logs_path, :method => :get %>
  <% elsif params[:type] %>
      <%= render :partial => @partial %>
      <%= button_to :cancel, time_logs_path, :method => :get %>
  <% else %>
      <%= render :partial => 'time_log_selector' %>
  <% end %>
</div>